# tutorial 捕获异常

```python
from fastapi import FastAPI, HTTPException

app = FastAPI()

```

## 自定义异常捕获，打印

```python
from typing import Any, Optional, Dict

from starlette.exceptions import HTTPException


class BaseHTTPException(HTTPException):
    STATUS_CODE = 400
    CODE = 40000
    MESSAGE = None

    def __init__(
            self,
            message: Any = None,
            status_code: int = 400,
            code: int = 40000,
            headers: Optional[Dict[str, Any]] = None
    ) -> None:
        self.message = message or self.MESSAGE
        self.status_code = status_code or self.STATUS_CODE
        self.code = code or self.CODE
        self.headers = headers

    def __repr__(self) -> str:
        class_name = self.__class__.__name__
        return f"{class_name}(status_code={self.status_code!r}, msg={self.message!r})"


class BadRequest(BaseHTTPException):
    STATUS_CODE = 400
    CODE = 40000
```

```python
import traceback

from fastapi import FastAPI, Request, status
from fastapi.exceptions import HTTPException, RequestValidationError
from fastapi.responses import JSONResponse


def log_message(request: Request, e):
    """打印 error 时的日志"""

    logger.error('start error'.center(60, '*'))
    logger.error(f'{request.method} {request.url}')
    logger.error(f'error is {e}')
    logger.error('end error'.center(60, '*'))


def register_exception(app: FastAPI):
    @app.exception_handler(RequestValidationError)
    async def validation_exception_handler(request: Request, exc: RequestValidationError):
        """捕获参数验证错误"""

        exc_str = f'{exc}'.replace('\n', ' ').replace('   ', ' ')
        log_message(request, exc_str)
        # content = exc.errors()
        content = {'code': Code.validator_error, 'message': exc_str}
        return JSONResponse(content=content, status_code=status.HTTP_422_UNPROCESSABLE_ENTITY)

    @app.exception_handler(UnauthorizedException)
    async def unauthorized_exception_handle(request: Request, exc: UnauthorizedException):
        """捕获UnauthorizedException"""

        log_message(request, exc.detail)
        content = {'code': Code.token_expired, 'message': exc.detail}
        return JSONResponse(content=content, status_code=exc.status_code)

    @app.exception_handler(NotFoundException)
    async def unauthorized_exception_handle(request: Request, exc: NotFoundException):
        """捕获NotFoundException"""

        log_message(request, exc.detail)
        content = {'code': Code.no_found, 'message': exc.detail}
        return JSONResponse(content=content, status_code=exc.status_code)

    @app.exception_handler(HTTPException)
    async def http_exception_handler(request: Request, exc: HTTPException):
        """捕获HTTPException"""

        log_message(request, exc.detail)
        content = {'code': Code.http_error, 'message': exc.detail}
        return JSONResponse(content=content, status_code=exc.status_code)

    @app.exception_handler(Exception)
    async def exception_handle(request: Request, exc: Exception):
        """捕获其他异常"""

        log_message(request, traceback.format_exc())
        content = {'code': Code.server_error, 'message': str(exc)}
        return JSONResponse(content=content, status_code=status.HTTP_500_INTERNAL_SERVER_ERROR)
```
